baseURL = "https://rfparty.xyz"
languageCode = "en-us"
title = "rfparty - a new way to see wireless"


theme = "hugo-story"
publishDir = "docs"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Dataparty"
  logo = "images/favicon.ico"
  favicon = true

[Params.social]
  github = "https://github.com/datapartyjs/rfparty-xyz"
  mastodon = "https://partyon.xyz/@rfparty"
  #twitter = "https://twitter.com/datapartydao"
  #facebook = "https://www.facebook.com/datapartydao"
  instagram = "https://www.instagram.com/datapartydao"
  youtube = "https://www.youtube.com/channel/UCi7MdWSJ6laGn0p11IuOuTA"
